config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index show create new] do
    resources :bookmarks, only: %i[create new]
  end
  delete 'bookmarks/:id', to: 'bookmarks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @movies = Movie.all
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    #params.require(:list).permit(:name, movie_ids: [])
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for @bookmark, url: list_bookmarks_path do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render "form", list: @list, bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "logo.jpg" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <%# if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "My lists", "#", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "New list", "#", class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Action", "#", class: "dropdown-item" %>
                  <%= link_to "Another action", "#", class: "dropdown-item" %>
                  <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <%# else %>
              <!--li class="nav-item"-->
                <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
              <!--/li-->
            <%# end %>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.association :movies, as: :check_boxes %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://undermoonlightsite.files.wordpress.com/2020/08/img_similarmovie-roomtheroom_2.jpg);">
  <div class="container">
    <h1>Save a movie. Any movie.</h1>
    <p>Seriously.</p>
  </div>
</div>
<div class="container">
  <div class="row-list-header">
    <h2>My lists</h2>
    <%= link_to "Create a new list", new_list_path, class: "btn btn-flat" %>
  </div>
  <div class="row">
  <% @lists.each do |list| %>
    <div class="col-sm-6">
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag list.photo.key, alt: "...", class: "card-img-top", crop: :fill %>
        <div class="card-body">
          <div class="card-text">
            <%= link_to list.name, list_path(list) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <%= link_to 'Add a bookmark', new_list_bookmark_path(@list) %>
</div>